# -*- coding: utf-8 -*-
"""supreme_court_judgement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v2ViBcx6DQs3pk4qAhCsXe0W9ZkZhiVH
"""
pip install faiss-cpu sentence-transformers pypdf transformers torch

import json
import faiss
import numpy as np
from pypdf import PdfReader
from sentence_transformers import SentenceTransformer, CrossEncoder
from transformers import pipeline

from pypdf import PdfReader

def load_pdf(file_path):
    reader = PdfReader(file_path)
    text = ""

    for page in reader.pages:
        text += page.extract_text() + "\n"

    return text


pdf_text = load_pdf("sample_data/docum.pdf")

print(pdf_text[:500])

def load_json(file_path):
    with open(file_path, "r") as f:
        data = json.load(f)
    return data

json_data = load_json("/content/sample_data/legal_clauses_5000_CLEAN.json")

def chunk_text(text, chunk_size=500, overlap=100):
    chunks = []

    start = 0
    while start < len(text):
        end = start + chunk_size
        chunk = text[start:end]
        chunks.append(chunk)
        start += chunk_size - overlap

    return chunks

pdf_chunks = chunk_text(pdf_text)

documents = []

for i, chunk in enumerate(pdf_chunks):
    documents.append({
        "text": chunk,
        "case_name": "Lease Agreement Document",
        "section": f"chunk_{i}"
    })

for item in json_data:
    documents.append({
        "text": item["clause"],
        "case_name": item["category"],
        "section": item["clause_id"]
    })

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

texts = [doc["text"] for doc in documents]

embeddings = embedding_model.encode(texts)
embeddings = np.array(embeddings).astype("float32")

dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)
index.add(embeddings)

def retrieve(query, top_k=5):

    query_embedding = embedding_model.encode([query]).astype("float32")

    distances, indices = index.search(query_embedding, top_k)

    results = [documents[i] for i in indices[0]]

    return results

reranker = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")

def rerank(query, retrieved_docs):

    pairs = [[query, doc["text"]] for doc in retrieved_docs]

    scores = reranker.predict(pairs)

    ranked = sorted(
        zip(retrieved_docs, scores),
        key=lambda x: x[1],
        reverse=True
    )

    return [doc for doc, score in ranked]

generator = pipeline(
    "text-generation",
    model="google/flan-t5-base"
)

def generate_answer(query, context_docs):

    context = "\n".join([doc["text"] for doc in context_docs[:3]])

    prompt = f"""
Answer the question using the legal context.

Context:
{context}

Question:
{query}

Answer:
"""

    result = generator(prompt, max_length=256)

    return result[0]["generated_text"]

def rag_pipeline(query):

    retrieved = retrieve(query)

    reranked = rerank(query, retrieved)

    answer = generate_answer(query, reranked)

    return answer, reranked

query = "What is Deed of Family Trust?"

answer, sources = rag_pipeline(query)

print("Answer:\n")
print(answer)

print("\nSources:\n")

for s in sources[:3]:
    print(s["case_name"], "-", s["section"])

